### ISSUE TITLE
Add new about section(Day 04)

### ISSUE THREAD

**Issue by Pavankumar07s** [FSOC-OSS/FSOC.V2#48]
You can take inspiration from any website

**Comment by iamvetruvian** [comment]
I have fixed this issue. 
![Screenshot_20241002_151739](https://github.com/user-attachments/assets/a45c2b61-0d76-474f-ab6e-a16bf4d5f901)

**Comment by ashum9** [comment]
i have fixed the is isue
![image](https://github.com/user-attachments/assets/8c2aeafd-e923-4a77-a528-3ece9dcbc3b7)

**Comment by ujjwal006** [comment]
I have fixed this issue.
